# Generated by Django 5.1.5 on 2025-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('residential_address_street_num', models.IntegerField()),
                ('residential_address_name', models.TextField()),
                ('residential_address_apt_num', models.IntegerField()),
                ('residential_address_zip', models.IntegerField()),
                ('dob', models.TextField()),
                ('date_registration', models.TextField()),
                ('party_aff', models.CharField(max_length=2)),
                ('precinct_num', models.IntegerField()),
            ],
        ),
    ]
