# Generated by Django 5.1.5 on 2025-04-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_address_apt_num',
            field=models.TextField(),
        ),
    ]
