# Generated by Django 5.1.5 on 2025-04-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_v20state_voter_v21primary_voter_v21town_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='residential_address_apt_num',
            new_name='apt_num',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='residential_address_name',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='residential_address_street_num',
            new_name='street_num',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='residential_address_zip',
            new_name='zip_code',
        ),
    ]
