# Generated by Django 5.1.5 on 2025-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_rename_residential_address_apt_num_voter_apt_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(),
        ),
    ]
