# Generated by Django 5.1.5 on 2025-04-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0005_alter_voter_apt_num_alter_voter_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
