# Generated by Django 5.1.5 on 2025-04-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0006_alter_voter_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_num',
            field=models.TextField(),
        ),
    ]
