# Generated by Django 5.1.5 on 2025-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='units',
            field=models.TextField(blank=True),
        ),
    ]
