# Generated by Django 5.1.5 on 2025-04-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_owneditem_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.TextField(blank=True),
        ),
    ]
