# Generated by Django 5.1.5 on 2025-04-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_ingredient_amount_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecollection',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='collection',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='project.recipecollection'),
            preserve_default=False,
        ),
    ]
