# Generated by Django 5.1.5 on 2025-04-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_recipecollection_recipes_recipe_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='collection',
        ),
        migrations.CreateModel(
            name='RecipeCollectionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.recipecollection')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.recipe')),
            ],
        ),
    ]
