# Generated by Django 5.1.5 on 2025-05-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_recipe_collection_recipecollectionrecipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProjectProfile',
        ),
        migrations.AlterModelTable(
            name='projectprofile',
            table='profile',
        ),
    ]
