# Generated by Django 5.1.5 on 2025-05-01 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_recipe_collection_recipecollectionrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProjectProfile',
        ),
        migrations.AlterField(
            model_name='owneditem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectprofile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectprofile'),
        ),
        migrations.AlterField(
            model_name='recipecollection',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectprofile'),
        ),
    ]
