# Generated by Django 5.1.5 on 2025-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectprofile_project_user_alter_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount_required',
            field=models.FloatField(blank=True),
        ),
    ]
