# Generated by Django 5.1.5 on 2025-02-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_profile_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
